### ISSUE TITLE
ReqIFParser.parse cannot parse reqifz files

### ISSUE THREAD

**Issue by greenpau** [strictdoc-project/reqif#64]
@stanislaw , would you be open to a PR that would allow to parse `reqifz` (arhived ReqIF) files?

Currently, the lib can only parse flat `.reqif` files.

**Comment by stanislaw** [comment]
Hi @greenpau! Sure, please go ahead!

**Comment by BobRollenhagen** [comment]
Hi @stanislaw, I have a branch ([reqifz](https://github.com/BobRollenhagen/reqif/tree/reqifz)) where I've taken a shot at a reqifz parser implementation. I created a new ReqIFZParser class which returns a RefIFZBundle which is a collection of ReqIFBundles and all of the attachments. Although this is working for my current needs, I'm not sure this is the best approach so I'd appreciate any feedback you have. I also considered adding a branch to the ReqIFParser.parse() to check if the file is a zipfile instead of a separate parser class.

**Comment by stanislaw** [comment]
I have checked your branch, and it looks very good to me. It would be great to see both parsing and unparsing implemented, so that we could do a round trip test: ReqIF -> ReqIFZ -> ReqIF.

An integration test could look like this:

- Start with a dummy ReqIF and a bunch of attached files (`input/` folder).
- "Unparse"/create a reqifz archive.
- Parse the reqifz back to ReqIF and a bunch of files but to another directory (`output/`).
- Compare the directories file by file and make sure that the files are the same.

This is an example of an integration test with an `expected/` folder.

This is how I do a file-by-file comparison in another project: https://github.com/strictdoc-project/strictdoc/blob/main/tests/end2end/end2end_test_setup.py#L54. That code could be extracted to a separate file and be put under `tests/integration` (note that there are similar tools like `expect_exit.py`).

The whole point of this is to ensure that there is an end-to-end testing of ReqIFz rountrip.

Let me know if the above sounds doable. Otherwise, I could do it myself, probably during the next weekend.

**Comment by stanislaw** [comment]
@BobRollenhagen , I have integrated your code and also added the unparsing code with a passthrough integration test.

I preserved your original commit but edited it slightly.

https://github.com/strictdoc-project/reqif/pull/132

My next step will be to write another test that makes sure that the attachments are also parsed/unparsed correctly. (The existing test only compares the ReqIF files, but not the attachments). When that is done, I will release a new Pip.

Thank you for showing me your branch. It certainly inspired me to complete the implementation based on your nice idea of storing the attachments as `bytes` in the ReqIFZBundle 👍

**Comment by stanislaw** [comment]
@BobRollenhagen 

I have released a new Pip version. Hopefully it does exactly what you wanted. I will test the integration with the parent StrictDoc project at some point to make sure I can work with ReqIFz files on that level.

Thank you again for your contribution!
